--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  :body: include run file.
full_name: Shell::CommandProcessor::run_config
is_singleton: true
name: run_config
params: ()
visibility: public
