--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Resolv::DNS::Config
includes: []

instance_methods: []

name: Config
superclass: Object
