--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  :body: INIT
constants: []

full_name: OpenSSL::ConfigError
includes: []

instance_methods: []

name: ConfigError
superclass: eOSSLError
