--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: JSON::JSONTreeView#configure_value
is_singleton: false
name: configure_value
params: (value, type)
visibility: private
