--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  :body: Returns an array of all combinations of elements from all arrays. The length of the returned array is the product of the length of ary and the argument arrays
- !ruby/struct:RDoc::Markup::Flow::VERB 
  :body: "   [1,2,3].product([4,5])     # =&gt; [[1,4],[1,5],[2,4],[2,5],[3,4],[3,5]]\n   [1,2].product([1,2])       # =&gt; [[1,1],[1,2],[2,1],[2,2]]\n   [1,2].product([3,4],[5,6]) # =&gt; [[1,3,5],[1,3,6],[1,4,5],[1,4,6],\n                              #     [2,3,5],[2,3,6],[2,4,5],[2,4,6]]\n   [1,2].product()            # =&gt; [[1],[2]]\n   [1,2].product([])          # =&gt; []\n"
full_name: Array#product
is_singleton: false
name: product
params: |
  ary.product(other_ary, ...)

visibility: public
