--- !ruby/object:RDoc::RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  :body: INIT
constants: 
- !ruby/object:RDoc::RI::Constant 
  comment: 
  name: DEFAULT_CONFIG_FILE
  value: rb_str_new2(default_config_file)
full_name: OpenSSL::Config
includes: 
- !ruby/object:RDoc::RI::IncludedModule 
  name: Enumerable
instance_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: "[]"
name: Config
superclass: Object
