--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: WEBrick::HTTPUtils::parse_qvalues
is_singleton: true
name: parse_qvalues
params: (value)
visibility: public
